events {}

http {
  server {
    listen 80;

    # Proxy to Jenkins under sub-path /jenkins/
    location /jenkins/ {
      proxy_pass http://jenkins:8080/jenkins/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_redirect off;
    }

    # Proxy to Python app as default landing page
    location / {
      proxy_pass http://python-app:8000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
  }
}
