apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deploy
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: nodejs
          image: arunagri03/node-app@sha256:bad66c5db232c9f7ede6a4f433efb73a033dfe071bec29c53a17f11c0ddd1f5e
          ports:
            - containerPort: 3000
