from flask import Flask
from prometheus_client import Counter, generate_latest, CONTENT_TYPE_LATEST, Gauge
from flask import Response
import random, time, threading

app = Flask(__name__)

# Define custom metrics
REQUEST_COUNT = Counter('app_requests_total', 'Total application HTTP requests', ['endpoint'])
RANDOM_GAUGE = Gauge('app_random_value', 'Random value generated by app')

# Simulate metric value updates
def update_gauge():
    while True:
        RANDOM_GAUGE.set(random.randint(1,100))
        time.sleep(5)

threading.Thread(target=update_gauge, daemon=True).start()

@app.route("/api")
def api():
    REQUEST_COUNT.labels(endpoint="/api").inc()
    return {"message": "Hello from API"}

@app.route("/")
def home():
    REQUEST_COUNT.labels(endpoint="/").inc()
    return {"message": "Welcome to the Home Page"}

@app.route("/metrics")
def metrics():
    return Response(generate_latest(), mimetype=CONTENT_TYPE_LATEST)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
